Repository mvilanova/intervals-mcp-server, pull requests merged in 2025-06, with the labels that each got.

#36 Create stale.yml
  .github/workflows/stale.yml
Labels: chore

#44 Accept athlete ids without i
  src/intervals_mcp_server/server.py
Labels: bug

#47 Fixes feel scale
  src/intervals_mcp_server/utils/formatting.py
Labels: bug

#51 Adds gitconfig to gitignore
  .gitignore
Labels: chore

#52 Fixes formatting for several wellness metrics
  src/intervals_mcp_server/utils/formatting.py
Labels: bug

#55 Update README.md
  README.md
Labels: documentation

#57 [intervals-mcp-server] delay API key validation
  src/intervals_mcp_server/server.py
Labels: bug, codex

#56 Switch to more structured format for creating workout steps
  src/intervals_mcp_server/server.py
  src/intervals_mcp_server/utils/types.py
  tests/test_server.py
Labels: enhancement
