Repository mvilanova/intervals-mcp-server, pull requests merged in 2025-05, with the labels that each got.

#14 Handle JSON decode errors in Intervals request
  src/intervals_mcp_server/server.py
  tests/test_make_intervals_request.py
Labels: codex

#15 Reuse shared AsyncClient
  src/intervals_mcp_server/server.py
  src/intervals_mcp_server/utils/formatting.py
Labels: codex

#16 Add unit tests and pytest configuration
  pyproject.toml
  tests/test_formatting.py
  tests/test_server.py
Labels: codex

#18 Bumps to Python 3.12 and updates readme and pyproject toml file
  README.md
  pyproject.toml
  uv.lock
Labels: enhancement

#19 Add contributor guide
  AGENTS.md
Labels: codex

#20 [intervals-mcp-server] Validates api key is not empty and athlete id matches expected pattern
  src/intervals_mcp_server/server.py
  tests/test_formatting.py
  tests/test_make_intervals_request.py
  tests/test_server.py
Labels: enhancement, codex

#21 Update README.md
  README.md
Labels: documentation

#28 Fixes uv.lock file to use pypi.org simple
  uv.lock
Labels: bug

#29 Adds tools uv section to pyproject.toml file
  pyproject.toml
Labels: enhancement

#30 Fix: use start_date_local key to get event date
  src/intervals_mcp_server/utils/formatting.py
Labels: bug
